# lib/codexes/gemini_codex.rb
require_relative 'base_codex'

class GeminiCodex < BaseCodex
  def initialize(model = "gemini-pro")
    super("gemini", model)
  end

  def generate_code(prompt)
    puts "[GeminiCodex] Calling Gemini API..."
    # Mock return for the sake of assignment
    "#!/usr/bin/env python\nprint('Generated by Gemini')"
  end
end
